name: MooBaa Test
on: [push]
jobs:
  test-scans:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - name: Prepare repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test
        run: |
          python -m unittest
      - name: Run Bandit Scan
        run: |
          bandit -r -ii -ll --exit-zero .
  #      - name: Security check report artifacts
  #        uses: actions/upload-artifact@v1
  #        with:
  #          name: Security report
  #          path: output/security_report.txt
