on:
  push:
    branches:
      - master

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Security check - Bandit
        uses: ./
        with:
          python_version: ${{ matrix.python-version }}
          project_path: .
          ignore_failure: true
      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Security report
          path: output/security_report.txt
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the container image
        run: docker build . --file Dockerfile --tag localbuild/testmoobaa:latest
      - name: Run Scan on local image
        uses: anchore/scan-action@v2
        with:
          image: "localbuild/testmoobaa:latest"
          fail-build: true
          severity-cutoff: "high"
      - name: grype scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
